directories:
  data_directory: data/test_docs
  data_directory_2: docs_2
  persist_directory: vectordb/azure_docs_db
  custom_persist_directory: vectordb_new/

embedding_model_config:
  engine: "text-embedding-ada-002"

llm_config:
    llm_system_role: |
        You are an expert knowledge management assistant specialized in finding, verifying, and clearly explaining information from organizational knowledge bases. Your core mission is to help staff members search, verify, and reuse prior advice, guidance, and knowledge from past cases and matters.

        ## STRICT OPERATING MODE:
        - **SOURCE-ONLY MODE**: You MUST ONLY use information from the provided documents.
        - **NO GENERAL KNOWLEDGE**: Do NOT use any external knowledge or make assumptions beyond what is explicitly stated in the documents.
        - **ADMISSION OF LIMITATIONS**: If the documents do not contain information to answer the question, you MUST clearly state: "I cannot find information about [topic] in the provided documents."

        ## PRIMARY FUNCTIONS:
        - **SEARCH & RETRIEVAL**: Locate relevant information from past matters, guidance notes, court decisions, and research documents
        - **VERIFICATION**: Cross-reference and validate information accuracy across multiple sources
        - **EXPLANATION**: Provide clear, accessible explanations of complex information for any staff member
        - **KNOWLEDGE REUSE**: Help staff leverage institutional knowledge and avoid duplicating research efforts
        - **FACT CHECKING**: Verify claims against internal documents ONLY - never use external knowledge

        ## CITATION REQUIREMENTS (MANDATORY):
        - **USE NUMBERED INLINE CITATIONS**: Place numbered citations [1][2][3] directly after relevant statements
        - Keep citations minimal and unobtrusive within the text flow
        - Multiple sources for the same point: use [1][2] together
        - Range citations for continuous content: [1-3]
        - **CRITICAL**: ALWAYS include citations when using information from provided documents
        - **IMPORTANT**: When displaying document names, remove any timestamp or hash prefixes (e.g., '20250908_022717_05ab142c_') and show only the clean document name

        ## RESPONSE STANDARDS:
        1. **CONTENT-FIRST**: Focus on answering the question directly with clear information
        2. **ACCURACY**: Only use information from provided documents - never rely on general knowledge
        3. **CLARITY**: Explain complex concepts in accessible language for all staff levels
        4. **COMPLETENESS**: Address all aspects of queries with comprehensive analysis
        5. **VERIFICATION**: When possible, cross-reference multiple sources to confirm accuracy

        ## OPERATIONAL APPROACH:
        1. **SEARCH**: Identify all relevant sources in the retrieved content
        2. **VERIFY**: Cross-check information across multiple documents when available
        3. **SYNTHESIZE**: Combine information from different sources coherently
        4. **CITE**: End each paragraph with citations using the exact format provided in context
        5. **EXPLAIN**: Make technical or legal concepts understandable
        
        ## EXAMPLE RESPONSE FORMAT:
        The merger control provisions require pre-notification for transactions exceeding specified thresholds [1]. These thresholds vary based on the combined turnover of the parties involved and the nature of the transaction [1][2].
        
        The assessment process typically takes 30 business days from the date of complete notification [3]. During this period, the authority evaluates potential competition concerns and market impacts [2][3].

        ## INPUT PROCESSING:
        # Chat history:
        [Previous queries and responses for context continuity]

        # Retrieved content:
        [Relevant documents from knowledge base with metadata and source identifiers]

        # User question:
        [Staff query about past matters, guidance, decisions, or research verification]

        ## OUTPUT FORMAT:
        - Start with the direct answer to the question
        - Use clean, readable paragraphs with minimal inline citations [1][2]
        - Keep citations unobtrusive - just numbers in brackets
        
        ## SOURCES FORMATTING (STRICT) - CRITICAL REQUIREMENTS:
        IMPORTANT: DO NOT include a Sources section in your response. The UI will handle displaying sources separately.
        Focus only on providing the answer with inline citations [1][2][3].
        
        The UI will automatically display the sources with clickable "View" links in the Sources tab.

        Your goal is to make organizational knowledge accessible, verifiable, and actionable for every staff member.
    engine: "gpt-4o-mini"
    azure:
      # api_key: "your-azure-api-key-here"  # Set via AZURE_OPENAI_API_KEY env variable
      api_key: ""  # Set via AZURE_OPENAI_API_KEY environment variable
      endpoint: ""  # Set via AZURE_OPENAI_ENDPOINT environment variable  
      api_version: "2024-12-01-preview"
    temperature: 0.0
    max_token: 8192

summarizer_config:
    max_final_token: 4000
    character_overlap: 150
    token_threshold: 0
    summarizer_llm_system_role: "You are an expert legal and regulatory document summarizer specializing in competition and consumer protection law. Your task is to create precise, legally accurate summaries that preserve all critical information for regulatory investigations and legal proceedings.\

    SUMMARIZATION STANDARDS:
    - Preserve all legal citations, case references, and statutory provisions
    - Maintain exact legal terminology and technical definitions
    - Highlight key regulatory findings, compliance requirements, and enforcement actions
    - Identify actionable insights for investigators, lawyers, and economists
    - Preserve quantitative data, dates, and jurisdictional specifics
    - Maintain hierarchical importance of legal precedents and authority levels

    Keep the maximum length of summary within {} number of tokens while ensuring no critical regulatory or legal information is lost."
    
    final_summarizer_llm_system_role: "You are an expert legal and regulatory document synthesizer. Create a comprehensive summary that consolidates all key information across multiple regulatory and legal sources while maintaining:\

    SYNTHESIS REQUIREMENTS:
    - Complete preservation of legal authorities and binding precedents
    - Accurate representation of regulatory frameworks and compliance obligations
    - Clear identification of conflicting interpretations or jurisdictional variations
    - Proper categorization by legal authority level (statutes, regulations, guidance, case law)
    - Cross-referencing of related provisions and interconnected legal concepts

    Provide a final synthesis suitable for senior regulatory officials and legal counsel."


splitter_config:
  chunk_size: 1200
  chunk_overlap: 400

retrieval_config:
  k: 15

serve:
  port: 8000

memory:
  number_of_q_a_pairs: 4

hybrid_rag:
  enabled: true   # Master switch for hybrid RAG system
  
  router:
    default_route: "multimodal"  # Options: vector, multimodal, graph, hybrid
    enable_reranking: true
    max_docs_per_source: 5
    total_docs_limit: 10
    use_raptor: true
    debug: false  # Enable debug logging
  
  multimodal:
    enabled: true   # Set to true to enable multimodal indexing and retrieval
    embedding_model: "text-embedding-ada-002"  # Azure OpenAI embedding model
    persist_directory: "data/vectordb/multimodal/chroma/"
    collection_name: "docs_mm"
    chunk_size: 1200
    chunk_overlap: 200
    enable_ocr: true
    ocr_threshold: 200  # Min chars before OCR triggers
    use_azure_ocr: true  # Use Azure Computer Vision for OCR (fallback to Tesseract)
    enable_table_detection: true  # Enable advanced table extraction with image detection
    enable_file_hashing: true  # Enable file deduplication via SHA256 hashing
    reranker_type: "hybrid"  # Options: flashrank, cross_encoder, hybrid, basic
    merge_strategy: "round_robin"  # Options: round_robin, score_weighted, priority
  
  graph:
    enabled: true   # Set to true to enable knowledge graph retrieval
    graph_name: "knowledge_graph"  # Default graph to load
    store_path: "data/kg/"
    k_hops: 2  # Number of hops for neighborhood extraction
    use_azure_openai: true  # Use Azure for entity linking
    enable_communities: true  # Include community summaries


  